version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: develop
  - package-ecosystem: npm
    directory: /
    ignore:
      - dependency-type: all
        update-types: ['version-update:semver-major']
    schedule:
      interval: daily
    target-branch: develop
